DATA PREPROCESSING

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [7]:
train_df = pd.read_csv("..\data\FraudTrain.csv")
test_df = pd.read_csv("..\data\FraudTest.csv")

#newtest  = test

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\BIT\AppData\Local\Temp\ipykernel_21188\181867111.py:1: SyntaxWarning: invalid escape sequence '\d'
  train_df = pd.read_csv("..\data\FraudTrain.csv")
C:\Users\BIT\AppData\Local\Temp\ipykernel_21188\181867111.py:2: SyntaxWarning: invalid escape sequence '\d'
  test_df = pd.read_csv("..\data\FraudTest.csv")

In [8]:
cols_to_drop = [
'Unnamed: 0','cc_num','first','last','street','trans_num'
]

train_df = train_df.drop(columns=cols_to_drop)
test_df = test_df.drop(columns=cols_to_drop)

In [9]:
# change date and time 
train_df['trans_date_trans_time'] = pd.to_datetime(train_df['trans_date_trans_time'])
test_df['trans_date_trans_time'] = pd.to_datetime(test_df['trans_date_trans_time'])

train_df['hour'] = train_df['trans_date_trans_time'].dt.hour
test_df['hour'] = test_df['trans_date_trans_time'].dt.hour

train_df = train_df.drop(columns=['trans_date_trans_time'])
test_df = test_df.drop(columns=['trans_date_trans_time'])



# change dob
train_df['dob'] = pd.to_datetime(train_df['dob'])
test_df['dob'] = pd.to_datetime(test_df['dob'])

train_df['age'] = 2026 - train_df['dob'].dt.year
test_df['age'] = 2026- test_df['dob'].dt.year

train_df = train_df.drop(columns=['dob'])
test_df = test_df.drop(columns=['dob'])



#Distance Feature (generally long distance )
train_df['distance'] = np.sqrt(
(train_df['lat'] - train_df['merch_lat'])**2 +
(train_df['long'] - train_df['merch_long'])**2
)

test_df['distance'] = np.sqrt(
(test_df['lat'] - test_df['merch_lat'])**2 +
(test_df['long'] - test_df['merch_long'])**2
)

In [10]:
train_df

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,hour,age,distance
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,Moravian Falls,NC,28654,36.0788,-81.1781,3495,"Psychologist, counselling",1325376018,36.011293,-82.048315,0,0,38,0.872830
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1325376044,49.159047,-118.186462,0,0,48,0.272310
2,fraud_Lind-Buckridge,entertainment,220.11,M,Malad City,ID,83252,42.1808,-112.2620,4154,Nature conservation officer,1325376051,43.150704,-112.154481,0,0,64,0.975845
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,Boulder,MT,59632,46.2306,-112.1138,1939,Patent attorney,1325376076,47.034331,-112.561071,0,0,59,0.919802
4,fraud_Keeling-Crist,misc_pos,41.96,M,Doe Hill,VA,24433,38.4207,-79.4629,99,Dance movement psychotherapist,1325376186,38.674999,-78.632459,0,0,40,0.868505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,fraud_Reichel Inc,entertainment,15.56,M,Hatch,UT,84735,37.7175,-112.4777,258,Geoscientist,1371816728,36.841266,-111.690765,0,12,65,1.177732
1296671,fraud_Abernathy and Sons,food_dining,51.70,M,Tuscarora,MD,21790,39.2667,-77.5101,100,"Production assistant, television",1371816739,38.906881,-78.246528,0,12,47,0.819632
1296672,fraud_Stiedemann Ltd,food_dining,105.93,M,High Rolls Mountain Park,NM,88325,32.9396,-105.8189,899,Naval architect,1371816752,33.619513,-105.130529,0,12,59,0.967541
1296673,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,M,Manderson,SD,57756,43.3526,-102.5411,1126,Volunteer coordinator,1371816816,42.788940,-103.241160,0,12,46,0.898775
1296674,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,M,Sula,MT,59871,45.8433,-113.8748,218,"Therapist, horticultural",1371816817,46.565983,-114.186110,0,12,31,0.786883

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [15]:
cat_col = ['merchant',"category",'gender','city','state','job']
encode = LabelEncoder()
for col in cat_col:
    train_df[col] = encode.fit_transform(train_df[col])
    test_df[col] = encode.fit_transform(test_df[col])

In [16]:
test_df

,merchant,category,amt,gender,city,state,zip,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud,hour,age,distance
0,319,10,2.86,1,157,39,29209,33.9659,-80.9355,333497,275,1371816865,33.986391,-81.200714,0,12,58,0.266004
1,591,10,29.84,0,16,43,84002,40.3207,-110.4360,302,392,1371816873,39.450498,-109.960431,0,12,36,0.991674
2,611,5,41.28,0,61,33,11710,40.6729,-73.5365,34496,259,1371816893,40.495810,-74.196111,0,12,56,0.682970
3,222,9,60.05,1,764,8,32780,28.5697,-80.8191,54767,407,1371816915,28.812398,-80.883061,0,12,39,0.250985
4,292,13,3.19,1,247,21,49632,44.2529,-85.0170,1126,196,1371816917,44.959148,-85.884734,0,12,71,1.118816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,507,5,43.77,1,443,23,63453,40.4931,-91.8912,519,460,1388534347,39.946837,-91.333331,0,23,60,0.780782
555715,264,7,111.84,1,401,42,77566,29.0393,-95.4401,28739,198,1388534349,29.661049,-96.186633,0,23,27,0.971537
555716,496,7,86.88,0,104,46,99323,46.1966,-118.9017,3684,294,1388534355,46.658340,-119.715054,0,23,45,0.935280
555717,75,13,7.99,1,476,12,83643,44.6255,-116.4493,129,58,1388534364,44.470525,-117.080888,0,23,61,0.650323
555718,125,0,38.13,1,224,35,73034,35.6665,-97.4798,116001,276,1388534374,36.210097,-97.036372,0,23,33,0.701517

MODEL TRAINING & DATA SPLITIING

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from imblearn.over_sampling import SMOTE

In [20]:
X_train = train_df.drop(columns=['is_fraud'])
y_train = train_df['is_fraud']

X_test = test_df.drop(columns=['is_fraud'])
y_test = test_df['is_fraud']

In [21]:
#using SMOTE
smote = SMOTE(random_state=42)

X_train, y_train = smote.fit_resample(X_train, y_train)

In [22]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
model1 = RandomForestClassifier(n_estimators=100, random_state=42)
model2 = model = xgb.XGBClassifier(n_estimators=100, learning_rate=0.1, )

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_parallel_tree=None, ...)

MODEL PREDICTION

In [ ]:
y_pred1 = model1.predict(X_test)

y_pred_prob = model2.predict_proba(X_test)[:,1]
y_pred2 = (y_pred_prob > 0.3).astype(int)

MODEL1 EVALUATION

In [31]:
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))
print("ROC AUC:", roc_auc_score(y_test, y_pred1))

[[552536   1038]
 [   662   1483]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    553574
           1       0.59      0.69      0.64      2145

    accuracy                           1.00    555719
   macro avg       0.79      0.84      0.82    555719
weighted avg       1.00      1.00      1.00    555719

ROC AUC: 0.8447501016555922

MODEL2 EVALUATION

In [32]:
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

print("ROC AUC:", roc_auc_score(y_test, y_pred_prob))

[[519683  33891]
 [   153   1992]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97    553574
           1       0.06      0.93      0.10      2145

    accuracy                           0.94    555719
   macro avg       0.53      0.93      0.54    555719
weighted avg       1.00      0.94      0.96    555719

ROC AUC: 0.9779843029432064